-- MySQL Script generated by MySQL Workbench
-- Wed Jan 24 14:55:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Posts` ;

CREATE TABLE IF NOT EXISTS `Posts` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  `content` VARCHAR(150) NULL,
  `dateFrom` DATETIME NULL,
  `dateUntil` DATETIME NULL,
  `priority` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_POSTS_USERS1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_POSTS_USERS1`
    FOREIGN KEY (`users_id`)
    REFERENCES `Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categories` ;

CREATE TABLE IF NOT EXISTS `Categories` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Comments` ;

CREATE TABLE IF NOT EXISTS `Comments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(150) NULL,
  `addTime` DATETIME NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_COMMENTAIRES_POSTS1_idx` (`posts_id` ASC) VISIBLE,
  CONSTRAINT `fk_COMMENTAIRES_POSTS1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Categories_has_Posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Categories_has_Posts` ;

CREATE TABLE IF NOT EXISTS `Categories_has_Posts` (
  `categories_id` INT NOT NULL,
  `posts_id` INT NOT NULL,
  PRIMARY KEY (`categories_id`, `posts_id`),
  INDEX `fk_Categories_has_Posts_Posts1_idx` (`posts_id` ASC) VISIBLE,
  INDEX `fk_Categories_has_Posts_Categories1_idx` (`categories_id` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_has_Posts_Categories1`
    FOREIGN KEY (`categories_id`)
    REFERENCES `Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Categories_has_Posts_Posts1`
    FOREIGN KEY (`posts_id`)
    REFERENCES `Posts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
